name: Compile ESP32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install esptool

    - name: Install PlatformIO
      run: |
        pip install platformio

    - name: Build firmware
      run: |
        platformio run

    - name: Upload firmware binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: .pio/build/*/*.bin
